### ISSUE TITLE
Couldn't view the amount due to keyboard hiding the input area

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#13]
**Specifications**

  - Application Version: burstcoin-wallet-0.1.0-rc.1.apk
  - Android Version: 6.0.1
  - Device: One Plus 2

**Expected Behavior**
when the user enters the value into the field should be receiving the focus and scroll to that input filed so the user could view the value entered.

**Actual Behavior & Screenshots**
when the user enters the value into the field the keyboard is hiding the input fields.

![screenshot_20170912-213919](https://user-images.githubusercontent.com/2860620/30355889-0bc463b0-9804-11e7-9ebf-bc341c90530c.png)

**Steps to Reproduce the Problem**
Refer the above screen shots

**Comment by rico666** [comment]
Yes - I consider this a big bummer too.
(I use this comment as a way to "vote" for a bug, similar like bugzilla and other bugtrackers have it to help with prio)
