### ISSUE TITLE
Send action makes application suspended 

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#15]
If you report a bug, please use the following template!

**Specifications**

  - Application Version: burstcoin-wallet-0.1.0-rc.1.apk
  - Android Version: 6.0.1
  - Device: One Plus 2

**Expected Behavior**
After sending the amount the application should show  balance tab with reduced amount

**Actual Behavior & Screenshots**
Application hangs for more than 30 to 40 seconds.
![screenshot_20170912-214034](https://user-images.githubusercontent.com/2860620/30356386-af8e446e-9806-11e7-8b20-5426542cbfde.png)

**Comment by cgebe** [comment]
Encountered multiple times? If yes, how can i reproduce it? Open for further investigation.

**Comment by NullNomad** [comment]
Yes, most of the time I get this issue. I think to count is I have multiple accounts in my wallets ..
