### ISSUE TITLE
Passphrase creation pattern - Created passphrases contains space between words and its not informed to user.

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#16]
New address creation process shows 12 random words and the user asked to retype those words to confirm the same matching. 

**Issue:**
During the retyping process user never enter space but the system seems to create passphrase with space between words which user is not aware of.

> It's common sense to include the spaces to differentiate the words but users usually be over cautious on passphrases of spaces in wallets. some users may get stuck with above use cases and easily frustrated

**Steps:**
1) I have created an account by generating below random words

> attract positive classic adware namibia aruba funeral editions xhtml johns keeping advice

2) I have noted down the passphrases I have entered as shown below. (no indication of spaces)

> attract positive classic adware namibia aruba funeral editions xhtml johns keeping advice

2) I have re entered the below words one by one by entering the words and selecting the shown word suggestions.

> attract positive classic adware namibia aruba funeral editions xhtml johns keeping advice

3) The account is created and I have noted down the passphrases I have entered as shown below. (Removed the spaces because I haven't entered any spaces in the second time when type and match the passphrase)

> attractpositiveclassicadwarenamibiaarubafuneraleditionsxhtmljohnskeepingadvice

Account created: BURST-K4Q5-TPTE-WCEV-8MTD8

 4) I have reinstalled the application and tried to import the active account with below passphrase but it creates a new account.
> attractpositiveclassicadwarenamibiaarubafuneraleditionsxhtmljohnskeepingadvice

5) When I try below passphrase which has spaces between the words seems to import correct account

> attract positive classic adware namibia aruba funeral editions xhtml johns keeping advice

**Suggestion:**

- we could inform them of spaces or remove the spaces when we create but it will be very confusing. 

- A simple solution would be to display passphrase as whole text after generation and ask them to note it down or copy to some pass lockers. Then let them reenter to match and generate the address.
It will be fast and simple. (I believe, Always less user interaction to achieve action results in better experience)

**Comment by NullNomad** [comment]
found out that the documentation has the test that its 12 words separated by space but in app message is missing this info !!

https://github.com/cgebe/burstcoin-wallet/blob/master/docs/wallet/create.md

**Comment by rico666** [comment]
Standard is the passphrase having spaces. It's also standard behavior of the reference implementation. Not sure what this is about.

**Comment by NullNomad** [comment]
For new users to crypto wallets and passphrases, this will be confusing !! we can update the messaging in application to convey that  "the 12 words are separated by spaces"

**Comment by rico666** [comment]
No, it will be not. PassPHRASE is exactly that. A Phrase. Not a Word.
https://en.wikipedia.org/wiki/Passphrase

**Comment by cgebe** [comment]
Documentation is for such issues: [Add Wallet](https://cgebe.github.io/burstcoin-wallet/wallet/create/)

**Comment by NullNomad** [comment]
yes that is my point also Rico, its phrase not words separated by spaces. @cgebe - we can't ask user to check docs and 90% of users who is using app not going to read the docs. I still stand a small update in label (which conveyes its 12/words separated by space is your passphrase)in application will reduce lot of support /answering from our side once we go live.
Anyway its closed but I thought of leaving the comment here. :-)

**Comment by rico666** [comment]
We can of course discuss this here post-mortem, but it's quite pointless. If you took the time to study the basic Wikipedia Link I have posted, you'd see the 1st sentence - and I quote: *"A passphrase is a sequence of words or other text used to control access to a computer system, program or data."* So actually a phrase IS words separated by spaces.

**Comment by rico666** [comment]
Oh I absolutely agree that the current "generate" workflow is tedious, but that is a different issue altogether. In fact your

3-step versus 38-step proposal

could have been a different issue as feature request.

**Comment by cgebe** [comment]
@NullNomad The passphrase generation/verification process was taken 1 by 1 from our reference model. Being tedious also has its benefits. Users **actually** write down their passphrase in a secure place. It is not sent by email, it is not copied into a memo and it is not just generated and without verification. If you have a better idea, please feel free to open a feature request.

Right now i changed the wording: "Write down the following words **separated by space** and keep them secret!". This will eliminate possible misunderstandings.

**Comment by NullNomad** [comment]
@cgebe  Yes that would do now and we will visit this after getting user feedbacks!

I agree it's an ideal scenario/recommended that users should write down and keep that paper passphrase safe. Do you have all of your BURST accounts passphrases in a paper?
I don't have all of my passphrase on paper and may be one day I will do that if I have thousands of BURST or BURST values go high.

We as developers overlook benefits in our view but most of the new normal users have just 1 to 3 minutes for us, we should onboard them in a couple of clicks and less typeing otherwise they just drop and not using it. 

This seems endless discussion and we will come back on this after we get some users feedbacks. I will open it as a feature if needed in future.
