### ISSUE TITLE
Feature Request: Delete Account

### ISSUE THREAD

**Issue by guelz** [cgebe/burstcoin-wallet#2]
If you report a bug, please use the following template!

**Specifications**

  - Application Version: 0.1.0 rc1
  - Android Version: 5.0.2
  - Device: LG G2 D502

**Expected Behavior**
"delete account" functionality

**Comment by cgebe** [comment]
[RC.2](https://github.com/cgebe/burstcoin-wallet/releases/tag/v0.1.0-rc.2)
