### ISSUE TITLE
Minor: Offline account balance is not update in account tab

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#22]
If you report a bug, please use the following template!

**Specifications**

- Application Version: beta
- Android Version: 6.0.1
- Device: One Plus 2

**Expected Behavior**
After importing the offline wallets, the user clicks the accounts tab and current balance should be displayed.
**Actual Behavior & Screenshots**
After importing the offline wallets, the user clicks the accounts tab and ZERO balance is displayed

**Steps to Reproduce the Problem**

1. Click import in accounts tab
2. Switch to offline wallets
3. Enter the burst address
4. Wallet gets imported and the user clicks Account tab and the newly imported account shows with zero balance.

Workaround:
 User have to pull down to refresh  the values for the newly added accounts

![screenshot_20170918-122450](https://user-images.githubusercontent.com/2860620/30553824-63a4ea30-9c70-11e7-9f50-6cb0317778ae.png)
![screenshot_20170918-122328](https://user-images.githubusercontent.com/2860620/30553832-679068ae-9c70-11e7-9dee-976914bcbfe1.png)

**Comment by cgebe** [comment]
There is no direct update? After pulling to refresh its updated?
