### ISSUE TITLE
Minor: icons style consistency

### ISSUE THREAD

**Issue by Gadrah** [cgebe/burstcoin-wallet#23]
The top menu displays four different icons, ideally they should be of the same style. However balance, history and setting icons are full black while accounts icon is transparent. No biggie but for better design consistency the accounts icon should be black too.

**Comment by cgebe** [comment]
Could you provide some screenshots, seems like a device dependent issue. There is also a change planned concerning the icon.

**Comment by Gadrah** [comment]
Sorry it wasn't clear. Currently the icon used is this one:

![screenshot](https://user-images.githubusercontent.com/32112962/30661763-47228e90-9e45-11e7-9e21-1fc0df402223.png)

I think it isn't exactly of the same design style as the 3 other. As an example something like that would mix better with the other icons:

![icon1](https://user-images.githubusercontent.com/32112962/30661866-89e69a78-9e45-11e7-8837-380b3b4087b9.png)

![screenshot2](https://user-images.githubusercontent.com/32112962/30661929-b8638618-9e45-11e7-96af-70720aa8c7f2.png)
