### ISSUE TITLE
Second account created with invalid address

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#3]
**Specifications**

  - Application Version: burstcoin-wallet-0.1.0-rc.1.apk
  - Android Version: 6.0.1
  - Device: One Plus 2

**Expected Behavior**
 Second account created with new valid BURST address  and user lands on accounts tab with new account listed as second account

**Actual Behavior & Screenshots**
Second account created with invalid address and account number shown as below in account tab
BURST-K4Q5-TPTE-LKGY-undefinedMTDundifined
13286281392458435

**Steps to Reproduce the Problem**

1) User has one account created and some transaction in it
2) User opts to create account in accounts tab by clicking + icon 
3) User created second account with passphrases 
4) second account created with invalid address and account number shown as below
BURST-K4Q5-TPTE-LKGY-undefinedMTDundifined
13286281392458435

![screenshot_20170911-151058](https://user-images.githubusercontent.com/2860620/30308477-c9776bc0-9753-11e7-8beb-14e1f8b14304.png)
![screenshot_20170911-151121](https://user-images.githubusercontent.com/2860620/30308480-cccdf1c2-9753-11e7-8dc7-300fe5f90f36.png)

**Comment by cgebe** [comment]
Can you provide me with the passphrase you have used? Seems that there a are artifacts in the generation.

**Comment by cgebe** [comment]
If you cannot share the passphrase, please check the generation again with [RC.2](https://github.com/cgebe/burstcoin-wallet/releases/tag/v0.1.0-rc.2)

**Comment by NullNomad** [comment]
Find below,

attract positive classic adware namibia aruba funeral editions xhtml johns keeping advice

**Comment by cgebe** [comment]
Issue resolved in rc.2
