### ISSUE TITLE
Lag after sending Burst

### ISSUE THREAD

**Issue by Nisc3d** [cgebe/burstcoin-wallet#33]
The app was really laggy after pressing the send Button.

- Application Version: 0.1.1
- Android Version: 7
- Device: Samsung Galaxy S7

Steps:
1. I started the app
2. I pressed send
3. I scanned the QR-Code of the address
4. I wrote the amount and pressed verify
5. I wrote my pin
6. I pressed send

**Comment by cgebe** [comment]
Could you be more specific? Did the app crash or didn't progress at all?

**Comment by Nisc3d** [comment]
No, it just responded slow afterwards.

**Comment by cgebe** [comment]
I'm working on performance improvements. However, make sure to have a sustainable internet connection when performing Burst payments. The payment process includes two requests to the Burst node:

- Announcing the Transaction
- Broadcasting the signed Transaction

Also if you encounter long waiting times, it may also be worth changing the Burst node to a node geographically near to your location.
