### ISSUE TITLE
Minor: Extra characters displayed when selecting accounts

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#4]
**Specifications**

  - Application Version: burstcoin-wallet-0.1.0-rc.1.apk
  - Android Version:  6.0.1
  - Device: One Plus 2

**Expected Behavior**
When switching accounts the messages shown at bottom should display switched account address

**Actual Behavior & Screenshots**
When switching accounts the messages shown at the bottom shows one extra character after the address.

![screenshot_20170912-005530 1](https://user-images.githubusercontent.com/2860620/30310015-57357670-975c-11e7-98a2-593f692426e6.png)

**Steps to Reproduce the Problem**
  1. Load the wallet
  2. select accounts tab with two accounts
  3. select any accounts

**Comment by cgebe** [comment]
resolved
