### ISSUE TITLE
Feature : Support for more languages and currency

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#5]
Feature:
1) Currently, the application supports BURST - BTC - USD and like to see BURST - BTC - EUR, BURST-BTC-YEN, BURST-BTC-INR, other major currencies.
2) Personalisation of wallets language in major languages.

Justification:
A wallet is something really boost a value/usability of coin and personalization of wallets with language/currency will make it world stage.

**Comment by rico666** [comment]
Again two distinct feature requests.

I consider the l10n being the more important one and am willing to help with translations when you have the .po files (or equivalent) I am willing to help with the translation (or delegating them).

I believe we can get german and spanish quite fast.
